export const getWalletDetails=async(req,res)=>{
    try {
        
        
    } catch (error) {
        
        console.log('Error',error);
        res.json({success:false,message:'Unknown error occured'})
    }
}